Repository unosquare/swan, pull requests merged in 2020-01, with the labels that each got.

#226 Fix, excluding ignored properties using JsonProperty
  src/Swan.Lite/Formatters/Json.SerializerOptions.cs
  test/Swan.Test/JsonTest.Serialize.cs
  test/Swan.Test/Mocks/JsonMock.cs
Labels: bug

#230 [FIX][BRK] Incorrect namespaces (closes #229)
  src/Swan.Lite/CompositeHashCode.cs
  src/Swan.Lite/Extensions.cs
  src/Swan.Lite/Logging/ConsoleLogger.cs
  src/Swan.Lite/Logging/DebugLogger.cs
  src/Swan.Lite/Logging/FileLogger.cs
  src/Swan.Lite/Logging/LogLevel.cs
  src/Swan.Lite/Logging/LogMessageReceivedEventArgs.cs
  src/Swan.Lite/Logging/TextLogger.cs
  src/Swan.Lite/Reflection/ConstructorTypeCache.cs
  src/Swan.Lite/Swan.Lite.csproj
  src/Swan.Lite/Terminal.Interaction.cs
  src/Swan/Net/ConnectionDataReceivedTrigger.cs
  test/Swan.Test/Mocks/LoggingEntryMock.cs
Labels: breaking change, bug, v2.x

#234 [ADD] Extension method Exception.RethrowPreservingStackTrace.
  src/Swan.Lite/Extensions.Exceptions.cs
Labels: enhancement, v2.x

#233 [FIX] IComponentCollection<T>.Add should declare name as nullable.
  src/Swan.Lite/Collections/ComponentCollection`1.cs
  src/Swan.Lite/Collections/IComponentCollection`1.cs
Labels: bug, v2.x
